const l108_ru={
"Abdominal Cramps":"Спазмы в животе",
"Abdominal Inflammation":"Воспаление брюшной полости",
"Abdominal Pain":"Боль в животе",
"Abscess Nocardia Asteroides":"Абсцесс Nocardia Asteroides",
"Abscesses 2":"Абсцессы 2",
"Abscesses 3":"Абсцессы 3",
"Abscesses Secondary":"Абсцессы вторичные",
"Abscesses":"Абсцессы",
"Absentmindedness":"рассеянность",
"Accelerate Healing":"Ускорить исцеление",
"Accelerate Injury Healing":"Ускорить заживление травм",
"Accelerate Learning":"Ускорить обучение",
"Accelerate Scar Healing":"Ускорить заживление шрамов",
"Acidosis":"Ацидоз",
"Acne 1":"прыщи 1",
"Acne 2":"прыщи 2",
"Acne Vulgaris Junior":"Акне Вульгарис Юниор",
"Acne Vulgaris":"Юношеские угри",
"Acne":"Угревая сыпь",
"Aconite":"Аконит",
"Acrocephalosyndactylia":"Акроцефалосиндактилия",
"Acromegaly":"Акромегалия",
"Actinobacillus":"актинобациллы",
"Actinomyces Bovis":"Актиномицеты Бовис",
"Actinomyces Israelii 1":"Актиномицеты израильские 1",
"Actinomyces Israelii 2":"Актиномицеты израильские 2",
"Actinomyces Israelii":"Актиномицеты израильские",
"Actinomycosis (Streptothrix)":"Актиномикоз (Стрептотрикс)",
"Actinomycosis 1":"Актиномикоз 1",
"Actinomycosis 2":"Актиномикоз 2",
"Actinomycosis Streptothrix MOR":"Актиномикоз Streptothrix MOR",
"Actinomycosis":"актиномикоз",
"Activity Increase":"Увеличение активности",
"Acupuncture Disturbance Field":"Поле нарушения акупунктуры",
"Acute Pain":"Острая боль",
"Addiction Alcoholism 1":"Наркомания Алкоголизм 1",
"Addiction Alcoholism 2":"Наркомания Алкоголизм 2",
"Addiction Drugs":"Наркотики",
"Addiction":"Зависимость",
"Addictions Alcohol General":"Наркомания Алкоголь Общее",
"Addictions Drug General":"Наркомания Общие сведения о наркотиках",
"Addison's Disease":"Болезнь Эддисона",
"Adeno-associated Virus":"Аденоассоциированный вирус",
"Adenoids":"Аденоиды",
"Adenoma Basal Cell":"Базально-клеточная аденома",
"Adenoma Beta-Cell":"Бета-клеточная аденома",
"Adenoma Cervical":"Аденома шейки матки",
"Adenoma Microcystic":"Аденома микрокистозная",
"Adenoma Monomorphic":"Аденома Мономорфная",
"Adenoma":"Аденома",
"Adenomatous Polyposis Coli (APC)":"Аденоматозный полипоз толстой кишки (АПК)",
"Adenomyosis":"Аденомиоз",
"Adenoviridae Infections":"Аденовирусные инфекции",
"Adenovirus 1":"Аденовирус 1",
"Adenovirus 2nd":"Аденовирус 2-й",
"Adenovirus 3rd":"Аденовирус 3-й",
"Adenovirus 4th":"Аденовирус 4-й",
"Adenovirus 5th":"Аденовирус 5-й",
"Adenovirus":"аденовирус",
"Adhesions Pelvic":"Спайки малого таза",
"Adhesions":"Спайки",
"Adhesive Capsulitis":"Адгезивный капсулит",
"Adiadochokinesis":"Адиадохокинез",
"Adie Syndrome":"Синдром Ади",
"Adiposis Dolorosa":"Долороза ожирения",
"Adnexitis":"аднексит",
"Adrenal Function Normalize":"Функция надпочечников нормализуется",
"Adrenal Gland Balance":"Баланс надпочечников",
"Adrenal Gland Diseases":"Заболевания надпочечников",
"Adrenal Gland Fever":"Лихорадка надпочечников",
"Adrenal Gland Stimulant 1":"Стимулятор надпочечников 1",
"Adrenal Gland Stimulant 2":"Стимулятор надпочечников 2",
"Adrenal Gland Stimulant 3":"Стимулятор надпочечников 3",
"Adrenal Gland Toxicity":"Токсичность надпочечников",
"Adrenal Hyperplasia":"Надпочечниковая гиперплазия",
"Adrenoleukodystrophy":"Адренолеукодистрофия",
"Adrenomyeloneuropathy":"Адреномиелоневропатия",
"Adverse Drug Reaction":"Побочная реакция на лекарство",
"Adynamia Geriatric":"Адинамия Гериатрическая",
"Afibrinogenemia":"афибриногенемия",
"Aflatoxin 1":"Афлатоксин 1",
"Aflatoxin 2":"Афлатоксин 2",
"Aflatoxin":"афлатоксин",
"African Lymphoma":"Африканская лимфома",
"African Trypanosomiasis":"Африканский трипаносомоз",
"Agammaglobulinemia":"Агаммаглобулинемия",
"Agitation":"Агитация",
"Agnosia":"Агнозия",
"Agyfla":"Агифла",
"Aicardi Syndrome":"Синдром Айкарди",
"AIDS 0":"СПИД 0",
"AIDS 1":"СПИД 1",
"AIDS 2":"СПИД 2",
"AIDS 3":"СПИД 3",
"AIDS Kaposi's Sarcoma":"СПИД Саркома Капоши",
"AIDS Secondary":"СПИД вторичный",
"AIDS":"СПИД",
"AIDS/HIV":"СПИД/ВИЧ",
"Airsickness":"воздушная болезнь",
"Akathisia":"акатизия",
"Alagille Syndrome":"Синдром Алажиля",
"Alcoholism 1":"Алкоголизм 1",
"Alcoholism 2":"Алкоголизм 2",
"Alcoholism":"Алкоголизм",
"Aldrich Syndrome":"Синдром Олдрича",
"Alertness Increase":"Повышение бдительности",
"Alexander Disease":"Александр Болезнь",
"Alignment of Individual":"Выравнивание личности",
"Alkalosis":"Алкалоз",
"Alkaptonuria":"Алкаптонурия",
"Allergic Granulomatous Angiitis":"Аллергический гранулематозный ангиит",
"Allergies 1":"Аллергии 1",
"Allergies 2":"Аллергии 2",
"Allergy Pollen":"Аллергия на пыльцу",
"Allergy":"аллергия",
"Alopecia 1":"Алопеция 1",
"Alopecia":"Алопеция",
"Alpha 1-Antitrypsin Deficiency":"Дефицит альфа-1-антитрипсина",
"Alpha Streptococcus 1":"Альфа-стрептококк 1",
"Alpha Streptococcus 2":"Альфа-стрептококк 2",
"Alpha Streptococcus 3":"Альфа-стрептококк 3",
"Alpha Streptococcus_1":"Альфа-стрептококк_1",
"Alpha Streptococcus_2":"Альфа-стрептококк_2",
"Alpha-Mannosidosis":"Альфа-маннозидоз",
"Alphavirus Infections":"Альфавирусные инфекции",
"ALS 1":"БАС 1",
"ALS 2":"БАС 2",
"ALS 3":"БАС 3",
"ALS 4":"БАС 4",
"Alternaria Tenuis":"Альтернария Тенуис",
"Aluminum 1":"Алюминий 1",
"Aluminum 2":"Алюминий 2",
"Alveolitis Fibrosing":"Альвеолит Фиброзирующий",
"Alzheimer Disease":"Болезнь Альцгеймера",
"Alzheimers 1":"болезнь Альцгеймера 1",
"Alzheimers 2":"болезнь Альцгеймера 2",
"Alzheimers 3":"болезнь Альцгеймера 3",
"Alzheimers 4":"болезнь Альцгеймера 4",
"Alzheimers":"болезни Альцгеймера",
"Amaurosis Fugax":"Амавроз Фугакс",
"Amblyopia":"амблиопия",
"Amenorrhea":"Аменорея",
"Amino Acid Metabolism":"Метаболизм аминокислот",
"Ammonia Remove":"Аммиак Удалить",
"Amnesia":"Амнезия",
"Amniotic Band Syndrome":"Синдром амниотической полосы",
"Amoeba General":"Амеба генерал",
"Amoeba Hepar Abscess":"Абсцесс амебы Hepar",
"Amoeba":"амеба",
"Amoebiasis":"амебиаз",
"Amoebic Dysentery":"Амебной дизентерией",
"Amphibian Diseases":"Земноводные Болезни",
"Amyloidosis":"Амилоидоз",
"Amyotonia Congenita":"Врожденная амиотония",
"Amyotrophic Lateral Sclerosis":"Боковой амиотрофический склероз",
"Anal Itching":"Анальный зуд",
"Analgesia":"обезболивание",
"Analgesic Pain Relief":"Обезболивающее обезболивающее",
"Analgesic":"Анальгетик",
"Anankastic Personality Disorder":"Ананкастическое расстройство личности",
"Anaphylaxis":"Анафилаксия",
"Anaplasma Lyme":"Анаплазма Лайма",
"Anaplasma Marginale 1":"Анаплазма Маргинале 1",
"Anaplasma Marginale 2":"Анаплазма Маргинале 2",
"Anaplasma Marginale 2nd":"Анаплазма Маргинале 2-й",
"Anaplasma Marginale 3":"Анаплазма Маргинале 3",
"Anaplasma Marginale":"Анаплазма Маргинале",
"Anaplasmosis":"Анаплазмоз",
"Ancylostoma Braziliense":"Анкилостома бразильская",
"Ancylostoma Caninum 1":"Анкилостома собачья 1",
"Ancylostoma Caninum 2":"Анкилостома собачья 2",
"Ancylostoma Caninum 3":"Анкилостома собачья 3",
"Ancylostoma Caninum_1":"Анкилостома Caninum_1",
"Ancylostoma Caninum_2":"Анкилостома Caninum_2",
"Ancylostoma Caninum_3":"Анкилостома Caninum_3",
"Androgen Insensitivity Syndrome":"Синдром нечувствительности к андрогенам",
"Anemia Aplastic":"Апластическая анемия",
"Anemia Hemolytic":"Гемолитическая анемия",
"Anemia Iron-Deficiency":"Железодефицитная анемия",
"Anemia Megaloblastic":"Мегалобластная анемия",
"Anemia":"анемия",
"Anencephaly":"Анэнцефалия",
"Aneurysm":"Аневризма",
"Angelman Syndrome":"Синдром Ангельмана",
"Anger and Irritability":"Гнев и раздражительность",
"Angina Pectoris":"стенокардия",
"Angina Throat":"Стенокардия горла",
"Angina":"Стенокардия",
"Angioedema":"ангионевротический отек",
"Angiofibroma":"Ангиофиброма",
"Angiolymphoid Hyperplasia with Eosinophilia":"Ангиолимфоидная гиперплазия с эозинофилией",
"Angiomyxoma":"Ангиомиксома",
"Anima/Soul":"Анима/Душа",
"Animal Diseases":"Болезни животных",
"Aniridia":"Аниридия",
"Anisakiasis":"анисакиоз",
"Anisocoria":"Анизокория",
"Ankyloglossia":"Анкилоглоссия",
"Ankylosing Spondylitis":"Анкилозирующий спондилоартрит",
"Anomia":"Аномия",
"Anophthalmos":"анофтальм",
"Anosmia":"Аносмия",
"Anoxia":"Аноксия",
"Anthracinum":"антрацин",
"Anthrax":"Сибирская язва",
"Anti-Glomerular Basement Membrane Disease":"Заболевание антигломерулярной базальной мембраны",
"Antidepressive":"антидепрессивное",
"Antimony 121sb":"Сурьма 121сб",
"Antimony 123sb":"Сурьма 123сб",
"Antiphospholipid Syndrome":"Антифосфолипидный синдром",
"Antiseptic General":"Общий антисептик",
"Antithrombin III Deficiency":"Дефицит антитромбина III",
"Anus Diseases":"Заболевания ануса",
"Anxiety 1":"Тревога 1",
"Anxiety Disorders":"Тревожные расстройства",
"Anxiety":"Беспокойство",
"Aortic Valve Stenosis":"Стеноз аортального клапана",
"Aphasia":"Афазия",
"Aphthovirus":"афтовирус",
"Apnea":"Апноэ",
"Apoplexy":"апоплексический удар",
"Appendicitis":"Аппендицит",
"Appetite Lack Of":"Отсутствие аппетита",
"Apraxias":"Апраксии",
"Aprosodia":"Апросодия",
"Arachnoid Cysts":"Арахноидальные кисты",
"Arachnoiditis":"Арахноидит",
"Araneae Thrush":"Арейский дрозд",
"Arbovirus Infections":"Арбовирусные инфекции",
"Aremes Tennus":"Аремес Теннус",
"Argentaffinoma":"Аргентаффинома",
"Arm Injuries":"Травмы рук",
"Arnica":"Арника",
"Arnold-Chiari Malformation":"Аномалия Арнольда-Киари",
"Arrhythmia Cardiac":"Сердечная аритмия",
"Arrhythmogenic Right Ventricular Dysplasia":"Аритмогенная дисплазия правого желудочка",
"Arsenic Aib.":"Мышьяк Аиб.",
"Arsenic Alb":"Мышьяк Альб",
"Arsenic as":"мышьяк как",
"Arsenic Poisoning":"Отравление мышьяком",
"Arteriosclerosis":"артериосклероз",
"Arteriovenous Malformations":"Артериовенозные мальформации",
"Artery Plaque":"Налет на артерии",
"Artery Stimulator":"Стимулятор артерий",
"Arthritis 1":"Артрит 1",
"Arthritis 2":"Артрит 2",
"Arthritis Arthralgia Due to Gout":"Артрит Артралгия из-за подагры",
"Arthritis Arthrosis and Parathyroid Disturbances Affecting Calcium Metabolism":"Артрит Артроз и нарушения паращитовидной железы, влияющие на метаболизм кальция",
"Arthritis General":"Общий артрит",
"Arthritis Gout":"артрит подагра",
"Arthritis Juvenile Chronic":"Ювенильный хронический артрит",
"Arthritis Juvenile Rheumatoid":"Ювенильный ревматоидный артрит",
"Arthritis Post-infectious":"Постинфекционный артрит",
"Arthritis Reactive":"Реактивный артрит",
"Arthritis Rheumatoid":"Ревматоидный артрит",
"Arthritis Secondary":"Вторичный артрит",
"Arthritis":"Артрит",
"Arthrogryposis":"Артрогрипоз",
"Arthropathy Neurogenic":"Артропатия Нейрогенная",
"Arthropod Diseases":"Болезни членистоногих",
"Asbestos in Lungs":"Асбест в легких",
"Asbestosis":"Асбестоз",
"Ascariasis":"аскаридоз",
"Ascaris Larvae":"Аскариды личинки",
"Ascaris Lumbricoides All Stages":"Ascaris Lumbricoides Все стадии",
"Ascaris Megalocephala (Male)":"Ascaris Megalocephala (самец)",
"Ascaris Megalocephala All Stages":"Ascaris Megalocephala на всех стадиях",
"Ascites 1":"Асцит 1",
"Ascites 2":"Асцит 2",
"Ascites":"Асцит",
"Ascorbic Acid Deficiency":"Дефицит аскорбиновой кислоты",
"Asian Grippe A":"Азиатский грипп А",
"Asperger Syndrome":"Синдром Аспергера",
"Aspergillosis":"Аспергиллез",
"Aspergillus Flavus":"Аспергилл Флавус",
"Aspergillus Glaucus":"Аспергилл глаукус",
"Aspergillus Niger":"Аспергилл Нигер",
"Aspergillus Terreus":"Аспергилл терреус",
"Asphyxia":"Асфиксия",
"Asthma 1":"Астма 1",
"Asthma 2":"Астма 2",
"Asthma 3":"Астма 3",
"Asthma 4":"Астма 4",
"Asthma 5":"Астма 5",
"Asthma Bronchial":"Бронхиальная астма",
"Asthma V":"Астма V",
"Asthma":"астма",
"Astigmatism":"Астигматизм",
"Astral Projection":"Астральная проекция",
"Astral Travel":"Астральное путешествие",
"Astrocytoma":"Астроцитома",
"Ataxia General":"Общая атаксия",
"Ataxia Spastic":"Спастическая атаксия",
"Ataxia Telangiectasia":"Атаксия Телеангиэктазия",
"Atelectasis Pulmonary":"Легочный ателектаз",
"Atherosclerosis":"Атеросклероз",
"Athletes Foot":"Спортсмены Фут",
"Atrial Fibrillation":"Мерцательная аритмия",
"Atrophy Muscular":"мышечная атрофия",
"Peroneal":"Перонеальный",
"Attention Deficit Disorder with Hyperactivity":"Синдром дефицита внимания с гиперактивностью",
"Attention Deficit Disorder":"Синдром дефицита внимания",
"Aura Builder":"Создатель ауры",
"Aura":"Аура",
"Auricular Cancer":"Рак ушной раковины",
"Autism":"аутизм",
"Autistic Disorder":"аутистическое расстройство",
"Auto Intoxication":"Авто опьянение",
"Autoimmune Diseases":"Аутоиммунные заболевания",
"Autoimmune Disorders":"Аутоиммунные заболевания",
"Autointoxication":"Автоинтоксикация",
"Autonomic Nervous System Diseases":"Заболевания вегетативной нервной системы",
"Avian Influenza":"Птичий грипп",
"Avitaminosis":"Авитаминоз",
"Awakening Epilepsy":"Пробуждающаяся эпилепсия",
"B Coli Filterable Virus":"Фильтруемый вирус B Coli",
"B Coli Rod Form":"Форма палочки B Coli",
"B Coli Rod":"Б Коли Род",
"B Coli Virus":"Вирус кишечной палочки",
"B Subtilis":"Б Субтилис",
"B-Cell Lymphoma":"В-клеточная лимфома",
"Babesia Lyme":"Бабезия Лайма",
"Babesia":"бабезия",
"Babesiosis":"бабезиоз",
"Bacillinum":"бациллин",
"Bacillus Anthracis 1":"Бацилла сибирской язвы 1",
"Bacillus Anthracis 2":"Бацилла сибирской язвы 2",
"Bacillus Anthracis 2nd range":"Бациллы сибирской язвы 2-го ряда",
"Bacillus Anthracis 2nd":"Бациллы сибирской язвы 2-й",
"Bacillus Anthracis 3":"Бацилла сибирской язвы 3",
"Bacillus Anthracis 3rd":"Бациллы сибирской язвы 3-й",
"Bacillus Anthracis 4":"Бацилла сибирской язвы 4",
"Bacillus Anthracis 5":"Бацилла сибирской язвы 5",
"Bacillus Anthracis Spores":"Споры бациллы сибирской язвы",
"Bacillus Anthracis":"Бацилла сибирской язвы",
"Bacillus Botulinus 6":"Бациллы ботулинуса 6",
"Bacillus Cereus 1":"Бацилла Цереус 1",
"Bacillus Cereus 2":"Бацилла Цереус 2",
"Bacillus Cereus":"Бацилла Цереус",
"Bacillus Coli Rod Form":"Палочковая форма Bacillus Coli",
"Bacillus Coli Virus":"Вирус бациллы палочки",
"Bacillus Infections":"Бациллезные инфекции",
"Bacillus Licheniformis":"Бацилла лихениформис",
"Bacillus Subtilis Niger 1":"Bacillus subtilis Нигер 1",
"Bacillus Subtilis Niger 2":"Bacillus subtilis Нигер 2",
"Bacillus Subtilis Niger 3":"Bacillus subtilis Нигер 3",
"Bacillus Subtilis Niger 4":"Bacillus subtilis Нигер 4",
"Bacillus Subtilis Niger_1":"Bacillus subtilis Нигер_1",
"Bacillus Subtilis Niger_2":"Bacillus subtilis Нигер_2",
"Bacillus Subtilis Niger_3":"Bacillus subtilis Нигер_3",
"Bacillus Subtilis":"бацилла сенная",
"Bacillus Thuringiensis":"Бацилла Тюрингенская",
"Bacillus X BX Cancer Carcinoma":"Bacillus X BX Рак Карцинома",
"Bacillus X Cancer Carcinoma":"Bacillus X Рак Карцинома",
"Bacillus X Filter Cancer Carcinoma":"Bacillus X Фильтр Рак Карцинома",
"Bacillus X":"Бацилла Х",
"Bacillus Y BY Cancer Sarcoma":"Bacillus Y BY Рак Саркома",
"Bacillus Y Cancer Sarcoma":"Bacillus Y Рак Саркома",
"Back Harm":"Назад Вред",
"Back Pain Generalized":"Боль в спине генерализованная",
"Back Pain Lower":"Боли в спине ниже",
"Back Pain Reduce":"Боль в спине уменьшить",
"Back Pain":"Боль в спине",
"Back Spasms":"Спазмы спины",
"Backache 1":"Боль в спине 1",
"Backache 2":"Боль в спине 2",
"Backache and Spasms 1":"Боли в спине и спазмы 1",
"Backache Chronic Lower 1":"Хроническая боль в спине 1",
"Bacteremia":"бактериемия",
"Bacteria General":"Бактерии Общие",
"Bacteria Lactis Nosode":"Бактерии Lactis Нозод",
"Bacterial Capsules (Capsular)":"Бактериальные капсулы (капсульные)",
"Bacterial Capsules 1":"Бактериальные капсулы 1",
"Bacterial Capsules 2":"Бактериальные капсулы 2",
"Bacterial Capsules":"Бактериальные капсулы",
"Bacterial Infections and Mycoses":"Бактериальные инфекции и микозы",
"Bacterial Infections Gram Positive":"Бактериальные инфекции грамположительные",
"Bacterial Infections":"Бактериальные инфекции",
"Bacterium Coli 1":"Бактерии Коли 1",
"Bacterium Coli 2":"Бактерии Коли 2",
"Bacterium Coli":"Бактерии Коли",
"Bacterium Lactis Nosode":"Бактерии Lactis Нозод",
"Bacteroides Fragilis 1":"Бактероиды ломкие 1",
"Bacteroides Fragilis 2":"Бактероиды ломкие 2",
"Bacteroides Fragilis 3":"Бактероиды ломкие 3",
"Bacteroides Fragilis 4":"Бактероиды ломкие 4",
"Bacteroides Fragilis":"Бактероиды ломкие",
"Bad Breath":"Неприятный запах изо рта",
"Bad Complexion":"Плохой цвет лица",
"Baker's Yeast Allergy":"Аллергия на пекарские дрожжи",
"Baker's Yeast":"Пекарские дрожжи",
"Balance":"Остаток средств",
"Balancing of Body":"Балансировка тела",
"Balanitis":"Баланит",
"Balantidium Coli Cysts 1":"Кисты Balantidium Coli 1",
"Balantidium Coli Cysts 2":"Кисты Balantidium Coli 2",
"Balantidium Coli Cysts":"Кисты балантидиев кишечной палочки",
"Banal":"Банальный",
"Bannayan-Zonana Syndrome":"Синдром Баннаяна-Зонана",
"Banti's Syndrome":"Синдром Банти",
"Barium 135ba 1":"Барий 135ба 1",
"Barium 137ba 2":"Барий 137ба 2",
"Barley Smut":"Ячменная головня",
"Barotrauma":"баротравма",
"Barrett's Esophagus 1":"Пищевод Барретта 1",
"Barrett's Esophagus":"Пищевод Барретта",
"Barth Syndrome":"синдром Барта",
"Bartonella Henslae":"Бартонелла Хенслае",
"Bartonella Infections":"Бартонеллезные инфекции",
"Bartonella Lyme":"Бартонелла Лайм",
"Bartonella Quintana":"Бартонелла Кинтана",
"Basal Cell Carcinoma":"Базально-клеточная карцинома",
"Basal Cell Nevus Syndrome":"Синдром базально-клеточного невуса",
"Basidiomycetes":"Базидиомицеты",
"BCG Vaccine":"Вакцина БЦЖ",
"Beals Syndrome":"Синдром Билса",
"Beauty":"Красота",
"Beckwith-Wiedemann Syndrome":"Синдром Беквита-Видеманна",
"Bed Wetting":"Недержание мочи",
"Bedsores 1":"Пролежни 1",
"Bedsores 3":"Пролежни 3",
"Bedsores":"Пролежни",
"Behcet Syndrome":"Синдром Бехчета",
"Bell's Palsy 1":"Паралич Белла 1",
"Bell's Palsy 2":"Паралич Белла 2",
"Bell's Palsy 3":"Паралич Белла 3",
"Bell's Palsy":"Паралич Белла",
"Berger's Disease":"Болезнь Бергера",
"Beriberi":"Бери-бери",
"Bermuda Smut":"Бермудская головня",
"Berylliosis":"Бериллиоз",
"Beryllium be":"Бериллий быть",
"Beryllium":"Бериллий",
"Besnoitia (Lung Sect.) Protozoan":"Besnoitia (Lung Sect.) Protozoan",
"Besnoitia 1":"Беснойтия 1",
"Besnoitia 2":"Беснойтия 2",
"Beta Streptococcus 1":"Бета-стрептококк 1",
"Beta Streptococcus 2":"Бета-стрептококк 2",
"Beta Streptococcus":"Бета-стрептококк",
"Beth Sutton's Bar Fungus":"Барный гриб Бет Саттон",
"Bile Duct Spasms and Pain":"Спазмы желчных протоков и боль",
"Bilharzia":"Бильгарзия",
"Biliary Atresia":"Билиарная атрезия",
"Biliary Cirrhosis":"Билиарный цирроз",
"Biliary Headache":"Билиарная головная боль",
"Biliary Tract Diseases":"Заболевания желчевыводящих путей",
"Biliousness 1":"Желтость 1",
"Biliousness 2":"Желтость 2",
"Biliousness":"Желчь",
"Bilirubin":"Билирубин",
"Bilirubinemia 1/2":"Билирубинемия 1/2",
"Biotinidase Deficiency":"Дефицит биотинидазы",
"Bipolar Disorder":"Биполярное расстройство",
"Bird Diseases":"Болезни птиц",
"Bird Flu Virus":"Вирус птичьего гриппа",
"Bird Tuberculosis":"Птичий туберкулез",
"Birt-Hogg-Dube Syndrome":"Синдром Берта-Хогга-Дюба",
"Bismuth bi":"Висмут би",
"Bites and Stings":"Укусы и укусы",
"Bites Insects":"Укусы насекомых",
"Biting of Insects":"Укусы насекомых",
"Black Death":"Черная смерть",
"Black Vomit":"Черная рвота",
"Black Widow Spider":"Черная вдова Паук",
"Blackheads":"угри",
"Blackwater Fever":"Черноводная лихорадка",
"Bladder and Prostate Complaints":"Жалобы на мочевой пузырь и простату",
"Bladder Diseases":"Заболевания мочевого пузыря",
"Bladder Exstrophy":"Экстрофия мочевого пузыря",
"Bladder Infection":"Инфекция мочевого пузыря",
"Bladder TBC":"мочевой пузырь",
"Bladder":"мочевой пузырь",
"Blastocystis Hominis Infections":"Инфекции Blastocystis Hominis",
"Blastocystis Hominis":"Бластоцистис Хоминис",
"Blepharisma":"Блефаризма",
"Blepharitis":"Блефарит",
"Blepharoptosis":"блефароптоз",
"Blepharospasm":"Блефароспазм",
"Blister":"Волдырь",
"Blood Capillaries Healing":"Заживление кровеносных капилляров",
"Blood Circulation Sluggish":"Кровообращение вялое",
"Blood Circulation Stimulate Normal":"Кровообращение Стимулировать Нормально",
"Blood Cleanser Cancer":"Очиститель крови от рака",
"Blood Cleanser":"Очиститель крови",
"Blood Clots":"Сгустки крови",
"Blood Coagulation Disorders":"Нарушения свертывания крови",
"Blood Conduction":"Проводимость крови",
"Blood Diseases":"Болезни крови",
"Blood Flow Increase":"Увеличение кровотока",
"Blood Flukes":"Кровяные сосальщики",
"Blood Hemoglobin Production":"Производство гемоглобина крови",
"Blood Hypertension":"Кровяная гипертензия",
"Blood Hypotention":"Кровяная гипотензия",
"Blood Plasma Cleaner":"Очиститель плазмы крови",
"Blood Platelet Disorders":"Заболевания тромбоцитов крови",
"Blood Pressure Balance 1":"Баланс артериального давления 1",
"Blood Pressure Balance 2":"Баланс артериального давления 2",
"Blood Pressure High Renin Induced":"Артериальное давление, вызванное высоким уровнем ренина",
"Blood Pressure High Spastic":"Артериальное давление высокое спастическое",
"Blood Pressure High":"Артериальное давление высокое",
"Blood Pressure Low":"Артериальное давление низкое",
"Blood Pressure Normalize":"Артериальное давление нормализуется",
"Blood Pressure Reduce":"Снижение артериального давления",
"Blood Purification":"Очищение крови",
"Blood Purify 1":"Очищение крови 1",
"Blood Red Cell Production":"Производство эритроцитов крови",
"Blood White Cell Production":"Производство лейкоцитов крови",
"Blood":"Кровь",
"Bloom Syndrome":"Синдром Блума",
"Blue Cohosh":"Голубой клопогон",
"Blue Rubber Bleb Nevus Syndrome":"Синдром синего резинового пузырькового невуса",
"Blue-green Algae":"Сине-зеленые водоросли",
"Boils 1":"Кипит 1",
"Boils Carbuncles":"Фурункулы Карбункулы",
"Boils Furunculosis":"Фурункулез",
"Boils Open":"фурункулы открытые",
"Boils Pus":"Фурункулы гной",
"Boils":"Нарывы",
"Bone Conduction":"Костная проводимость",
"Bone Disease and Periodontal":"Заболевания костей и пародонта",
"Bone Disease Periodontal Disease":"Болезни костей Пародонтоз",
"Cavity":"полость",
"Bone Diseases":"Заболевания костей",
"Bone Fractures":"Переломы костей",
"Bone Growth":"Рост костей",
"Bone Neoplasms":"Костные новообразования",
"Bone Regeneration 1":"Костная регенерация 1",
"Bone Regeneration":"Регенерация кости",
"Bone Spur 1":"Костяная шпора 1",
"Bone Spur 2":"Костяная шпора 2",
"Bone Spurs":"Костные шпоры",
"Bone Stimulate Healing":"Стимулирование заживления костей",
"Bone Stimulation":"Костная стимуляция",
"Bone Trauma 2":"Костная травма 2",
"Bone Trauma":"Костная травма",
"Bone":"Кость",
"Bones Stimulate Healing":"Кости стимулируют заживление",
"Bordetella Parapertussis 1":"Бордетелла Парапертуссис 1",
"Bordetella Parapertussis 2":"Бордетелла Парапертуссис 2",
"Bordetella Pertussis 1":"Бордетелла коклюшная 1",
"Bordetella Pertussis 2":"Бордетелла коклюша 2",
"Bordetella Pertussis 3":"Бордетелла коклюша 3",
"Bordetella Pertussis 4":"Бордетелла коклюша 4",
"Bordetella Pertussis":"Бордетелла коклюша",
"Borna Disease Virus BDV":"Вирус болезни Борна BDV",
"Borna Disease":"Болезнь Борна",
"Boron 10b":"Бор 10b",
"Boron 11b":"Бор 11б",
"Borrelia Afzelli Lyme 6":"Боррелия Афцелли Лайм 6",
"Borrelia Burgdorferi 1":"Боррелия Бургдорфери 1",
"Borrelia Burgdorferi 2":"Боррелия Бургдорфери 2",
"Borrelia Burgdorferi Lyme Disease":"Болезнь Лайма Borrelia Burgdorferi",
"Borrelia Burgdorferi Lyme":"Боррелия Бургдорфери Лайм",
"Borrelia Garinii Lyme":"Боррелия Гарини Лайм",
"Borrelia Hatchlings and Eggs":"Детеныши и яйца боррелий",
"Borrelia Lyme 1":"Боррелия Лайм 1",
"Borrelia Lyme 2":"Боррелия Лайм 2",
"Borrelia Lyme 3":"Боррелия Лайм 3",
"Borrelia Lyme 4":"Боррелия Лайм 4",
"Borrelia Lyme 5":"Боррелия Лайм 5",
"Borrelia Lyme A":"Боррелия Лайм А",
"Borrelia Lyme B":"Боррелия Лайм Б",
"Borrelia Lyme JB":"Боррелия Лайм JB",
"Borrelia Lyme Secondary":"Средняя школа боррелии Лайм",
"Borrelia Lyme Tertiary":"Боррелия Лайма третичная",
"Borrelia Spirochete A":"Боррелия Спирохета А",
"Borrelia Spirochete B":"Боррелия Спирохета B",
"Borrelia Spirochete Inhabited Microbes":"Боррелии, спирохеты, населенные микробами",
"Borrelia Spp. Cysts":"виды боррелий. кисты",
"Borrelia":"Боррелия",
"Borreliosis 1":"Боррелиоз 1",
"Borreliosis 2":"Боррелиоз 2",
"Borreliosis 3":"Боррелиоз 3",
"Borreliosis":"боррелиоз",
"Botrytis Cinereas":"Ботритис цинереас",
"Botrytis":"Ботритис",
"Botulinum":"ботулинический",
"Botulism":"ботулизм",
"Bowen's Disease":"Болезнь Боуэна",
"Brachial Neuralgia":"Плечевая невралгия",
"Brachial Plexus Neuritis":"Неврит плечевого сплетения",
"Bradycardia":"Брадикардия",
"Brain 1":"Мозг 1",
"Brain Abscess":"Абсцесс мозга",
"Brain Beta Stimulate":"Бета-стимуляция мозга",
"Brain Cell Energise":"Энергия клеток мозга",
"Brain Concussion":"Сотрясение мозга",
"Brain Diseases":"Заболевания головного мозга",
"Brain Frontal Lobe":"Лобная доля мозга",
"Brain Fungus 1":"Мозговой грибок 1",
"Brain Fungus 2":"Мозговой грибок 2",
"Brain Ischemia":"Ишемия головного мозга",
"Brain Normalize":"Мозг нормализуется",
"Brain Tumor 1":"Опухоль головного мозга 1",
"Brain Tumor 2":"Опухоль головного мозга 2",
"Brain Tumor Astrocytoma":"Опухоль головного мозга Астроцитома",
"Brain":"Головной мозг",
"Branched-Chain Ketoaciduria":"Кетоацидурия с разветвленной цепью",
"Branchio-Oto-Renal Syndrome":"Бранхио-ото-ренальный синдром",
"Branhamella Catarrhalis 2":"Бранхамелла катарралис 2",
"Branhamella Catarrhalis":"Бранхамелла катарралис",
"Branhamella Moraxella Catarrhalis":"Бранхамелла Моракселла Катаралис",
"Branhamella Neisseria Catarrhalis 1":"Branhamella Neisseria Catarrhalis 1",
"Branhamella Neisseria Catarrhalis 2":"Branhamella Neisseria Catarrhalis 2",
"Breakbone Fever":"Переломная лихорадка",
"Breast Cancer":"Рак молочной железы",
"Breast Cyst":"Киста молочной железы",
"Breast Diseases":"Заболевания груди",
"Breast Fibroid Cysts 2":"Кисты молочной железы 2",
"Breast Fibroid Cysts":"Кисты молочной железы",
"Breast Fibromatosis 1":"Грудь Фиброматоз 1",
"Breast Fibromatosis 2":"Грудь Фиброматоз 2",
"Breast Inflammation":"Воспаление груди",
"Breast Neoplasms Male":"Новообразования молочной железы у мужчин",
"Breast Neoplasms":"Новообразования молочной железы",
"Breast Sore Nipples":"соски",
"Breast Tumors Benign":"Доброкачественные опухоли молочной железы",
"Breast Tumors":"Опухоли молочной железы",
"Breathe Easier":"Дышите легче",
"Breathing Deep":"Дыхание глубоко",
"Breathing Difficulty (Dyspnea)":"Затрудненное дыхание (одышка)",
"Breathing":"Дыхание",
"Bright's Syndrome 1":"Синдром Брайта 1",
"Bright's Syndrome":"Синдром Брайта",
"Bromine 79br":"Бром 79бр",
"Bromine 81br":"Бром 81бр",
"Bronchial Asthma 1":"Бронхиальная астма 1",
"Bronchial Asthma 3":"Бронхиальная астма 3",
"Bronchial Asthma 4":"Бронхиальная астма 4",
"Bronchial Asthma 5":"Бронхиальная астма 5",
"Bronchial Asthma 6":"Бронхиальная астма 6",
"Bronchial Asthma":"Бронхиальная астма",
"Bronchial Diseases":"Бронхиальные заболевания",
"Bronchial Pneumonia 1":"Бронхиальная пневмония 1",
"Bronchial Pneumonia 2":"Бронхиальная пневмония 2",
"Bronchial Pneumonia 3":"Бронхиальная пневмония 3",
"Bronchial Pneumonia":"Бронхиальная пневмония",
"Bronchiectasis":"Бронхоэктазы",
"Bronchiolitis":"Бронхиолит",
"Bronchitis 1":"Бронхит 1",
"Bronchitis 2":"Бронхит 2",
"Bronchitis Secondary":"Бронхит вторичный",
"Bronchitis":"Бронхит",
"Broncho Pneumonia Borinum":"Бронхо-пневмония Боринум",
"Broncho Pulmonary Dysplasia":"Бронхолегочная дисплазия",
"Brown Recluse Spider 1":"Коричневый паук-отшельник 1",
"Brown Recluse Spider 2":"Коричневый паук-отшельник 2",
"Brown Recluse Spider":"Коричневый паук-отшельник",
"Brown Sequard Syndrome":"Синдром Брауна-Секара",
"Brucella Abort Bang":"бруцелла прервать взрыв",
"Brucella Melitensis":"Бруцелла мелитензис",
"Brucellosis":"бруцеллез",
"Bruises":"синяки",
"Bruxism":"Бруксизм",
"Bryozoa Cristatalla":"Мшанка Cristatalla",
"Bubonic Plague 1":"Бубонная чума 1",
"Bubonic Plague 2":"Бубонная чума 2",
"Bubonic Plague Secondary Infections":"Вторичные инфекции бубонной чумы",
"Bubonic Plague Yersinia Pestis":"Бубонная чума Yersinia Pestis",
"Bubonic Plague":"Бубонная чума",
"Budd-Chiari Syndrome":"Синдром Бадда-Киари",
"Bulbar Palsy Progressive":"Бульбарный паралич Прогрессирующий",
"Bulbospinal Neuropathy":"Бульбоспинальная невропатия",
"Bulla":"Булла",
"Bunion Pain":"боль в косточке",
"Bunions":"бурсит",
"Bunyaviridae Infections":"Буньявирусные инфекции",
"Burkholderia Infections":"Буркхолдериозные инфекции",
"Burkitt Lymphoma":"Лимфома Беркитта",
"Burning Mouth Syndrome":"Синдром горящего рта",
"Burns":"Бернс",
"Bursitis 2":"Бурсит 2",
"Bursitis":"Бурсит",
"BX Virus 1":"Вирус ВХ 1",
"BX Virus 2":"Вирус ВХ 2",
"BX Virus a":"BX вирус а",
"BX Virus":"Вирус ВХ",
"BY Human to Human Contact":"ЧЕЛОВЕЧЕСКИЙ КОНТАКТ",
"BY Virus 3":"ПО Вирусу 3",
"BY Virus":"ПО Вирусу",
"C":"С",
"Cadmium 111cd":"Кадмий 111cd",
"Cadmium 113cd":"Кадмий 113cd",
"Cadmium":"Кадмий",
"Caeliacia":"Целиакия",
"Cafe-au-Lait Spots":"Кофе с молоком",
"Caffey-De Toni-Silvermann Syndrome":"Синдром Кэффи-Де Тони-Сильверманна",
"Calcifications":"Обызвествления",
"Calcium 2":"Кальций 2",
"Calcium Metabolism Improve":"Метаболизм кальция улучшается",
"Calcium Metabolism":"Метаболизм кальция",
"Calcium on Heart Valve":"Кальций на сердечном клапане",
"Calcium Uptake Reduce":"Уменьшение усвоения кальция",
"Caliciviridae Infections":"Калицивирусные инфекции",
"Calming 1":"Успокаивающий 1",
"Calming 4":"Успокаивающий 4",
"Calming":"успокаивающий",
"Campylobacter 1":"Кампилобактер 1",
"Campylobacter 2":"Кампилобактер 2",
"Campylobacter Fetus Smear 1":"Кампилобактерный мазок плода 1",
"Campylobacter Fetus Smear 2":"Кампилобактерный мазок плода 2",
"Campylobacter Fetus Smear":"Кампилобактерный мазок плода",
"Campylobacter Infections":"Кампилобактерные инфекции",
"Campylobacter Pyloridis 1":"Кампилобактер пилоридис 1",
"Campylobacter Pyloridis 2":"Кампилобактер пилоридис 2",
"Campylobacter Pyloridis":"Кампилобактер пилоридис",
"Campylobacter":"Кампилобактер",
"Canavan Disease":"Болезнь Канавана",
"Cancer 1 Healing":"Рак 1 Исцеление",
"Cancer 4 W1":"Рак 4 П1",
"Cancer 4 W2":"Рак 4 П2",
"Cancer Additional Frequencies 1":"Дополнительные частоты рака 1",
"Cancer Additional Frequencies 2":"Дополнительные частоты рака 2",
"Cancer Adenocarcinoma Esophageal":"Рак Аденокарцинома Пищевода",
"Cancer Adenoma":"Раковая аденома",
"Cancer All Tumors":"Рак Все опухоли",
"Cancer Always":"Рак всегда",
"Cancer Astrocytoma":"Рак Астроцитома",
"Cancer Basal Cell Skin Carcinoma":"Рак Базальноклеточный рак кожи",
"Cancer Basic 1":"Рак Базовый 1",
"Cancer Basic 2":"Рак Базовый 2",
"Cancer Basic 3":"Рак Базовый 3",
"Cancer Basic 4":"Рак Базовый 4",
"Cancer Basic 5":"Рак Базовый 5",
"Cancer Basic 6":"Рак Базовый 6",
"Cancer Basic 7":"Рак Базовый 7",
"Cancer Basic 8":"Рак Базовый 8",
"Cancer Basic 9":"Рак Базовый 9",
"Cancer Basic A":"Рак Базовый А",
"Cancer Basic Set":"Базовый набор Рак",
"Cancer Bladder 2":"Рак мочевого пузыря 2",
"Cancer Bladder 3":"Рак мочевого пузыря 3",
"Cancer Bladder 4":"Рак мочевого пузыря 4",
"Cancer Bladder TBC":"Рак мочевого пузыря TBC",
"Cancer Bladder":"Рак мочевого пузыря",
"Cancer Blood Multiple Melanoma":"Рак Кровь Множественная Меланома",
"Cancer Bone":"Раковая кость",
"Cancer Brain Tumor":"Раковая опухоль головного мозга",
"Cancer Breast 1":"Рак груди 1",
"Cancer Breast 2":"Рак груди 2",
"Cancer Breast 3":"Рак груди 3",
"Cancer Breast":"Рак груди",
"Cancer Breast 4":"Рак груди 4",
"Cancer Breast 5":"Рак груди 5",
"Cancer Breast 6":"Рак груди 6",
"Cancer Bronchial":"Рак Бронхиальный",
"Cancer BX Carcinoma Virus 1":"Рак BX Вирус карциномы 1",
"Cancer BX Carcinoma Virus 2":"Рак BX Вирус карциномы 2",
"Cancer BX Carcinoma Virus 3":"Рак BX Вирус карциномы 3",
"Cancer BX Carcinoma Virus 4":"Рак BX Вирус карциномы 4",
"Cancer BX Virus":"Вирус рака BX",
"Cancer BX":"Рак БХ",
"Cancer BXBY":"Рак BXBY",
"Cancer BY Sarcoma Virus 1":"Рак, вызванный вирусом саркомы 1",
"Cancer BY Sarcoma Virus 2":"Рак, вызванный вирусом саркомы 2",
"Cancer BY Sarcoma Virus 3":"Рак, вызванный вирусом саркомы 3",
"Cancer BY Virus":"Рак от вируса",
"Cancer Carcinoid Tumor Gastrointestinal":"Рак Карциноидная опухоль Желудочно-кишечный тракт",
"Cancer Carcinoma 1":"Рак Карцинома 1",
"Cancer Carcinoma 3":"Рак Карцинома 3",
"Cancer Carcinoma Basal Cell Skin 1":"Рак Карцинома Базально-клеточная кожа 1",
"Cancer Carcinoma Basal Cell Skin":"Рак Карцинома Базально-клеточная кожа",
"Cancer Carcinoma Bronchial":"Рак Карцинома Бронхиальная",
"Cancer Carcinoma Colon":"Карцинома толстой кишки",
"Cancer Carcinoma General":"Рак Карцинома Общие",
"Cancer Carcinoma Larynx":"Рак Карцинома гортани",
"Cancer Carcinoma Liver 1":"Рак Карцинома печени 1",
"Cancer Carcinoma Liver 2":"Рак Карцинома печени 2",
"Cancer Carcinoma Liver Fermentative":"Рак Карцинома Печень Ферментативный",
"Cancer Carcinoma Original Crane":"Рак Карцинома Оригинальный кран",
"Cancer Carcinoma Scan 2":"Сканирование раковой карциномы 2",
"Cancer Carcinoma Scan":"Сканирование раковой карциномы",
"Cancer Carcinoma Uterine Fermentative":"Рак Карцинома матки Ферментативный",
"Cancer Carcinoma":"Рак Карцинома",
"Cancer Cell Repair Octal":"Octal для восстановления раковых клеток",
"Cancer Cell Repair Scalar":"Скаляр восстановления раковых клеток",
"Cancer Cells Conidium Head":"Головка конидия раковых клеток",
"Cancer Cells":"Раковые клетки",
"Cancer Cervical 1":"Рак шейки матки 1",
"Cancer Cervical 2":"Рак шейки матки 2",
"Cancer Cervical":"Рак шейки матки",
"Cancer Colon":"Рак толстой кишки",
"Cancer Conidium Head Cells":"Головные клетки раковых конидий",
"Cancer Digestive System":"Пищеварительная система рака",
"Cancer Droglioma":"Раковая дроглиома",
"Cancer Ear":"Ухо Рака",
"Cancer Endocrine Gland":"Рак эндокринной железы",
"Cancer Endometrium":"Рак эндометрия",
"Cancer Esophageal":"Рак пищевода",
"Cancer Ewings PNET":"Рак Юингс PNET",
"Cancer Experimental Additional Frequencies":"Экспериментальные дополнительные частоты рака",
"Cancer Experimental Additional":"Рак Экспериментальный Дополнительный",
"Cancer Extracranial Germ Cell Tumor":"Рак Экстракраниальная опухоль зародышевых клеток",
"Cancer Extracranial Tumor":"Раковая экстракраниальная опухоль",
"Cancer Extrahepatic Bile Duct":"Рак внепеченочных желчных протоков",
"Cancer Eye Cancer Intraocular Melanoma":"Рак Рак Глаза Внутриглазная Меланома",
"Cancer Eye Cancer":"Рак Рак Глаза",
"Cancer Feline Cat":"Кошка Рак",
"Cancer Fibrosarcoma":"Рак Фибросаркома",
"Cancer Fibrous Tumor Secondary":"Рак Волокнистая опухоль Вторичная",
"Cancer Frequencies":"Частоты рака",
"Cancer Gallbladder":"Рак желчного пузыря",
"Cancer Gastric":"Рак желудка",

"Cancer General 1":"Генерал Рак 1",
"Cancer General 2":"Генерал Рак 2",
"Cancer General 3":"Генерал Рак 3",
"Cancer General Scan":"Общее сканирование рака",
"Cancer General Set 1":"Общий набор рака 1",
"Cancer General Set 2":"Общий набор рака 2",
"Cancer General Set 3":"Общий набор рака 3",
"Cancer General":"Общий Рак",
"Cancer Genital Female":"Женский Рак Генитальный",
"Cancer Genital Male":"Рак Генитальный Мужчина",
"Cancer Genital Neoplasms Female":"Рак Генитальные Новообразования Женский",
"Cancer Genital Neoplasms Male":"Рак Генитальные Новообразования Мужской",
"Cancer Germ Cell Tumor Extragonadal":"Рак Герминогенная опухоль Внегонадная опухоль",
"Cancer Germ Cell":"Раковая зародышевая клетка",
"Cancer Gestational Trophoblastic Tumor":"Рак Гестационная трофобластическая опухоль",
"Cancer Gestational Tumor":"Рак Гестационная Опухоль",
"Cancer Glioblastoma Tremor":"Рак Глиобластома Тремор",
"Cancer Glioblastoma":"Раковая глиобластома",
"Cancer Gliomas":"Раковые глиомы",
"Cancer Hairy Cell":"Волосатая клетка рака",
"Cancer Head and Neck":"Рак головы и шеи",
"Cancer Hodgkin's Disease 2":"Рак Болезнь Ходжкина 2",
"Cancer Hodgkin's Disease":"Рак Болезнь Ходжкина",
"Cancer HPV (Moles and Tumors)":"Рак ВПЧ (родинки и опухоли)",
"Cancer Hypopharyngeal":"Рак гортани",
"Cancer Intestinal":"Рак кишечника",
"Cancer Islet Cell Carcinoma":"Раковая островковая клеточная карцинома",
"Cancer Kaposi's Sarcoma":"Рак Саркома Капоши",
"Cancer Larynx":"Рак гортани",
"Cancer Leukemia":"Рак Лейкемия",
"Cancer Leukemia Feline":"Рак Лейкемия Кошачий",
"Cancer Leukemia Hairy Cell":"Волосатые клетки рака лейкемии",
"Cancer Leukemia Lymphatic":"Рак Лейкемия Лимфатическая",
"Cancer Leukemia T Cell":"Рак Лейкемия Т-клетка",
"Cancer Lip and Oral Cavity":"Рак губ и полости рта",
"Cancer Liver Cancer":"Рак Рак печени",
"Cancer Liver Carcinoma 1":"Рак Карцинома печени 1",
"Cancer Liver Carcinoma 2":"Рак Карцинома печени 2",
"Cancer Liver Carcinoma Fermentative":"Рак Карцинома печени Ферментативный",
"Cancer Liver":"Рак печени",
"Cancer Lung Non-Small Cell":"Рак легкого немелкоклеточный",
"Cancer Lung Small Cell":"Мелкоклеточный рак легкого",
"Cancer Lung":"Рак легкого",
"Cancer Lymphatic":"Рак лимфатический",
"Cancer Lymphogranuloma Lymphoma 2":"Рак Лимфогранулема Лимфома 2",
"Cancer Lymphogranuloma Lymphoma":"Рак Лимфогранулема Лимфома",
"Cancer Lymphogranuloma Venereum Secondary":"Рак лимфогранулема венерическая вторичная",
"Cancer Lymphogranuloma Venereum":"Венерическая лимфогранулема рака",
"Cancer Lymphoma 1":"Раковая лимфома 1",
"Cancer Lymphoma 2":"Раковая лимфома 2",
"Cancer Lymphoma B-Cell":"Раковая лимфома В-клеточная",
"Cancer Lymphoma Non-Hodgkin's":"Раковая лимфома Неходжкинская болезнь",
"Cancer Lymphoma":"Раковая лимфома",
"Cancer Lymphosarcoma":"Раковая лимфосаркома",
"Cancer Maintenance":"Поддержание рака",
"Cancer Malignant Mesothelioma":"Рак Злокачественная мезотелиома",
"Cancer Melanoma 1":"Рак Меланома 1",
"Cancer Melanoma 2":"Рак Меланома 2",
"Cancer Melanoma Metastasis":"Метастаз меланомы рака",
"Cancer Melanoma":"Рак Меланома",
"Cancer Merkel Cell Carcinoma":"Рак Карцинома из клеток Меркеля",
"Cancer Merkel Cell":"Раковая клетка Меркель",
"Cancer Metasatic Squamous Neck":"Метастатическая плоскоклеточная опухоль шеи",
"Cancer Mouth":"Рот Рака",
"Cancer Multiple Myeloma 1":"Рак Множественная миелома 1",
"Cancer Multiple Myeloma":"Рак Множественная миелома",
"Cancer Multiple Myeloma/Plasma Cell Neoplasms":"Рак Множественная миелома/плазмоклеточные новообразования",
"Cancer Mycosis Fungoides":"Грибовидный микоз рака",
"Cancer Myelodysplastic Syndrome":"Раковый миелодиспластический синдром",
"Cancer Myeloid":"Миелоидный рак",
"Cancer Myeloproliferative Disorders":"Раковые миелопролиферативные заболевания",
"Cancer Myeloproliferative":"Рак Миелопролиферативный",
"Disorders":"расстройства",
"Cancer Nasopharyngeal 2":"Рак носоглотки 2",
"Cancer Nasopharyngeal":"Рак носоглотки",
"Cancer Nervous System Neoplasms":"Раковые новообразования нервной системы",
"Cancer Neuroblastoma":"Рак Нейробластома",
"Cancer Non Hodgkins 1":"Рак Не Ходжкинс 1",
"Cancer Non Hodgkins 2":"Рак Не Ходжкинс 2",
"Cancer Not Killed by Freqs 2008 and 2128":"Рак не убивают Freqs 2008 и 2128",
"Cancer Oral":"Рак Оральный",
"Cancer Oropharyngeal":"Рак ротоглотки",
"Cancer Osteosarcoma":"Рак Остеосаркома",
"Cancer Otorhinolaryngologic Neoplasms":"Рак Оториноларингологические Новообразования",
"Cancer Otorhinolaryngologic":"Рак Оториноларингологический",
"Cancer Ovarian":"Рак яичников",
"Cancer Pain":"Раковая боль",
"Cancer Pancreatic 1":"Рак поджелудочной железы 1",
"Cancer Pancreatic 2":"Рак поджелудочной железы 2",
"Cancer Pancreatic Exocrine and Islet Cell":"Экзокринная и островковая клетка рака поджелудочной железы",
"Cancer Paranasal Sinus and Nasal Cavity":"Рак околоносовых пазух и полости носа",
"Cancer Parathyroid":"Рак паращитовидной железы",
"Cancer Pheochromocytoma":"Рак Феохромоцитома",
"Cancer Pituitary":"Рак гипофиза",
"Cancer Plasma Cell Neoplasm":"Рак Плазмоклеточная Новообразование",
"Cancer Plasmacytoma":"Рак Плазмоцитома",
"Cancer Prostate 1":"Рак простаты 1",
"Cancer Prostate 2":"Рак простаты 2",
"Cancer Prostate 3":"Рак простаты 3",
"Cancer Prostate 4":"Рак простаты 4",
"Cancer Prostate":"Рак простаты",
"Cancer Rectal":"Рак Ректальный",
"Cancer Residual":"Остаточный рак",
"Cancer Respiratory Tract Neoplasms":"Рак Новообразования дыхательных путей",
"Cancer Rhabdomyosarcoma Embryonal":"Рак Рабдомиосаркома Эмбриональный",
"Cancer Rhabdomyosarcoma Embryonal Vega 1":"Рак Рабдомиосаркома Эмбриональная Вега 1",
"Cancer Rhabdomyosarcoma":"Рак Рабдомиосаркома",
"Cancer Salivary Gland":"Рак слюнной железы",
"Cancer Sarcoma 2":"Рак Саркома 2",
"Cancer Sarcoma General Resonant Light Alternate Set":"Рак Саркома Общий Резонансный Свет Альтернативный Набор",
"Cancer Sarcoma General":"Рак Саркома Общее",
"Cancer Sarcoma":"Рак Саркома",
"Cancer Sezary Syndrome":"Рак Сезари Синдром",
"Cancer Skin":"Раковая кожа",
"Cancer Small Intestine":"Рак тонкой кишки",
"Cancer Squamous Cell Carcinoma":"Рак Плоскоклеточная карцинома",
"Cancer Stomach 2":"Рак желудка 2",
"Cancer Stomach 3":"Рак желудка 3",
"Cancer Stomach 4":"Рак желудка 4",
"Cancer Stomach":"Рак желудка",
"Cancer T Cell":"Раковая Т-клетка",
"Cancer Tertiary":"Рак Третичный",
"Cancer Testicular":"Рак яичка",
"Cancer Thoracic Neoplasms":"Раковые новообразования грудной клетки",
"Cancer Thoracic":"Рак грудной клетки",
"Cancer Throat BX Sweep 1":"Раковое горло BX Sweep 1",
"Cancer Throat BX Sweep 2":"Раковое горло BX Sweep 2",
"Cancer Throat Tumor 1":"Раковая опухоль горла 1",
"Cancer Throat Tumor 2":"Раковая опухоль горла 2",
"Cancer Thymoma Malignant":"Рак Тимома Злокачественная",
"Cancer Thymoma":"Рак Тимома",
"Cancer Thyroid":"Рак щитовидной железы",
"Cancer Tonsil":"Рак миндалин",
"Cancer Trophoblastic Neoplasms":"Раковые трофобластические новообразования",
"Cancer Trophoblastic":"Рак Трофобластический",
"Cancer Tumors":"Раковые опухоли",
"Cancer Urethral":"Рак уретры",
"Cancer Urinary Bladder Neoplasms":"Рак мочевого пузыря Новообразования",
"Cancer Urologic Neoplasms":"Рак Урологические новообразования",
"Cancer Uterine Cervical Neoplasms":"Рак матки Новообразования шейки матки",
"Cancer Uterine Fermentative":"Рак матки Ферментативный",
"Cancer Uterine Sarcoma":"Рак матки Саркома",
"Cancer Uterine":"Рак матки",
"Cancer Vulvar":"Рак вульвы",
"Cancer Wilms' Tumor":"Раковая опухоль Вильмса",
"Cancer":"Рак",
"Cancrum Oris 2":"Канкрам Орис 2",
"Cancrum Oris":"Канкрам Орис",
"Candida 1":"Кандида 1",
"Candida 2":"Кандида 2",
"Candida 3":"Кандида 3",
"Candida 4":"Кандида 4",
"Candida Albicans 1":"Кандида Альбиканс 1",
"Candida Albicans 2":"Кандида Альбиканс 2",
"Candida Albicans 3":"Кандида Альбиканс 3",
"Candida Albicans 4":"Кандида Альбиканс 4",
"Candida Albicans 7":"Кандида Альбиканс 7",
"Candida Albicans":"Грибковые микроорганизмы албиканс",
"Candida and Organ Support 1":"Candida и поддержка органов 1",
"Candida and Organ Support 2":"Candida и поддержка органов 2",
"Candida Carcinomas":"Кандидозные карциномы",
"Candida HiPower":"Кандида ХайПауэр",
"Candida LoPower":"Кандида ЛоПауэр",
"CUST":"КАСТ",
"Candida Organ Support":"Поддержка органов Candida",
"Candida Overgrowth":"Разрастание кандиды",
"Candida Secondary":"Кандида вторичная",
"Candida Sweep":"Кандидозная развертка",
"Candida Tertiary":"Кандида третичная",
"Candida Tropicalis 1":"Кандида Тропикалис 1",
"Candida Tropicalis 2":"Кандида Тропикалис 2",
"Candida Tropicalis":"Кандида тропическая",
"Candida":"Кандида",
"Candidiasis Vulvovaginal":"Кандидоз вульвовагинальный",
"Candidiasis":"Кандидоз",
"Canine Mutant Strain":"Собачий мутантный штамм",
"Canine Parvo B":"Собачий Парво Б",
"Canine Parvo Mutant":"Собачий парвовирусный мутант",
"Canine Parvo":"Собачий парвовирус",
"Canine Parvovirus Mutant Strain":"Мутантный штамм собачьего парвовируса",
"Canine Parvovirus Type B":"Собачий парвовирус типа B",
"Canine Parvovirus":"Собачий парвовирус",
"Canker Sore 1":"Язвенная болезнь 1",
"Canker Sore 2":"Рана язвы 2",
"Canker Sore 3":"Язвенная болезнь 3",
"Canker Sore 4":"язвенная болезнь 4",
"Canker":"Рак",
"Capgras Syndrome":"Синдром Капгра",
"Capillaria Hepatica (Liver Sect)":"Capillaria Hepatica (печеночная секта)",
"Capillaria Hepatica":"Капиллярия печеночная",
"Capillaries Healing":"Капилляры Исцеление",
"Capillaries Stimulate Healing":"Капилляры стимулируют заживление",
"Carbo Animalis":"Карбо Анималис",
"Carbohydrate-Deficient Glycoprotein Syndrome":"Синдром углеводно-дефицитного гликопротеина",
"Carbon c":"Углерод с",
"Carbuncles 2":"Карбункулы 2",
"Carbuncles":"Карбункулы",
"Carbuncles 4":"Карбункулы 4",
"Carcinoid Tumor":"Карциноидная опухоль",
"Carcinoma 1":"Карцинома 1",
"Carcinoma 2":"Карцинома 2",
"Carcinoma 3":"Карцинома 3",
"Carcinoma Basal Cell":"Базально-клеточная карцинома",
"Carcinoma Bronchial":"Бронхиальная карцинома",
"Carcinoma Colon":"Рак толстой кишки",
"Carcinoma Liver Fermentative":"Карцинома печени ферментативная",
"Carcinoma Merkel Cell":"Карцинома Меркеля клетки",
"Carcinoma Non-Small Cell Lung":"Карцинома немелкоклеточного легкого",
"Carcinoma Oat Cell":"Карцинома овсяной клетки",
"Carcinoma Skin Basal Cell":"Базальноклеточный рак кожи",
"Carcinoma Small Cell":"Мелкоклеточная карцинома",
"Carcinoma Uterine Fermentative":"Карцинома матки Ферментативная",
"Carcinoma":"Карцинома",
"Carcinomatosis":"Карциноматоз",
"Cardiac Hypertrophy":"Сердечная гипертрофия",
"Cardiac Tamponade":"Сердечная тампонада",
"Cardiacedema":"отек сердца",
"Cardiomyopathy Congestive":"Кардиомиопатия Застойная",
"Cardiomyopathy Dilated":"Кардиомиопатия дилатационная",
"Cardiomyopathy Hypertrophic":"Кардиомиопатия Гипертрофическая",
"Cardiomyopathy Restrictive":"Кардиомиопатия рестриктивная",
"Cardiovascular Diseases":"Сердечно-сосудистые заболевания",
"Carnitine Disorders":"Карнитиновые расстройства",
"Caroli Disease":"Болезнь Кароли",
"Carotid Artery Narrowing":"Сужение сонной артерии",
"Carotid Stenosis":"Каротидный стеноз",
"Carpal Tunnel Secondary":"Кистевой туннельный вторичный",
"Carpal Tunnel Syndrome 1":"Синдром запястного канала 1",
"Carpal Tunnel Syndrome 2":"Синдром запястного канала 2",
"Carpal Tunnel Syndrome 3":"Кистевой туннельный синдром 3",
"Carpal Tunnel Syndrome":"Кистевой туннельный синдром",
"Cartilage and Connective Tissue":"Хрящ и соединительная ткань",
"Cartilage Diseases":"Заболевания хрящей",
"Carvularia Spirafera":"Карвулярия Спирафера",
"Cat Diseases":"Болезни кошек",
"Cat Eye Syndrome":"Синдром кошачьего глаза",
"Cat Scratch Fever":"Лихорадка от кошачьих царапин",
"Cat Virus":"Кошачий вирус",
"Cataract 1":"Катаракта 1",
"Cataract":"Катаракта",
"Cataract 3":"Катаракта 3",
"Cataract Brunescent":"катаракта брунесцентная",
"Cataract Complicated":"Катаракта осложненная",
"Cataract General 1":"Катаракта Общая 1",
"Catarrh 1":"Катар 1",
"Catarrh 4":"Катар 4",
"Catarrh":"Катар",
"Catheterization":"Катетеризация",
"Cattle Diseases":"Болезни крупного рогатого скота",
"Causalgia":"каузалгия",
"Causticum":"Каустикум",
"Cavernitis Fibrous":"Кавернит фиброзный",
"Cavus Deformity":"Деформация кавуса",
"Celia Carroll":"Селия Кэрролл",
"Celiac Disease":"Целиакия",
"Cell Regeneration":"Регенерация клеток",
"Cells of Leudig":"Клетки Леудига",
"Cellulitis":"Целлюлит",
"Cementoma":"цементома",
"Centering Frequency":"Центрирующая частота",
"Central Cord Syndrome":"Центральный пуповинный синдром",
"Central Core Disease":"Болезнь центрального стержня",
"Central Nervous System Diseases":"Заболевания центральной нервной системы",
"Central Nervous System Infections":"Инфекции центральной нервной системы",
"Central Nervous System Master":"Мастер центральной нервной системы",
"Central Spores (Bacillus Smear)":"Центральные споры (мазок Bacillus)",
"Cephalosporium":"цефалоспориоз",
"Cephalothecium":"Цефалотеций",
"Cerclage Cervical":"Серкляж шейки матки",
"Cerebellar Ataxia":"Мозжечковая атаксия",
"Cerebral Gigantism":"Церебральный гигантизм",
"Cerebral Hemorrhage":"Кровоизлияние в мозг",
"Cerebral Palsy":"церебральный паралич",
"Cerebro Spinal Trouble":"Церебро-спинальная проблема",
"Cerebrohepatorenal Syndrome":"Цереброгепаторенальный синдром",
"Cerebrospinal Conditions":"Цереброспинальные заболевания",
"Cerebrovascular Disorders":"Цереброваскулярные расстройства",
"Cerumen Ear Wax":"Серная ушная сера",
"Cerumen":"Серумен",
"Cervic Adenoma":"Аденома шейки матки",
"Cervic Gland Lumps":"Уплотнения шейной железы",
"Cervical Cancer":"Рак шейки матки",
"Cervical Inflammation":"Воспаление шейки матки",
"Cervical Polyp":"Цервикальный полип",
"Cervicitis":"Цервицит",
"Cervix Adenoma":"Аденома шейки матки",
"Cervix Incompetence":"Несостоятельность шейки матки",
"Cesium cs":"Цезий cs",
"Cestode Infections":"Цестодозные инфекции",
"Chaetomium Globosum":"Хетомиум шаровидный",
"Chagas Disease":"Болезнь Шагаса",
"Chakra 2 3rd Eye":"Чакра 2 3-й глаз",
"Chakra 2 Base":"Чакра 2 База",
"Chakra 2 Chain":"Цепь Чакры 2",
"Chakra 2 Crown":"Чакра 2 Корона",
"Chakra 2 Heart":"Чакра 2 Сердце",
"Chakra 2 Sacral":"Чакра 2 Сакральная",
"Chakra 2 Solar Plexus":"Чакра 2 Солнечное сплетение",
"Chakra 2 Throat":"Чакра 2 Горло",
"Chakra 3rd Eye":"Чакра третьего глаза",
"Chakra Base Root":"Базовый корень чакры",
"Chakra Base":"База Чакры",
"Chakra Crown":"Чакра Корона",
"Chakra Heart":"Чакра Сердце",
"Chakra Sacral":"Чакра Сакральная",
"Chakra Solar Plexus":"Чакра солнечного сплетения",
"Chakra Throat":"Чакра Горло",
"Chalazion":"Халазион",
"Chancre":"Шанкр",
"Chancroid Ulcers":"Шанкроидные язвы",
"Chancroid":"Мягкий шанкр",
"Change Facilitating":"Изменение",
"Changes":"Изменения",
"Charcot-Marie-Tooth Disease":"Болезнь Шарко-Мари-Тута",
"CHARGE Syndrome":"ЗАРЯД синдром",
"Chediak-Higashi Syndrome":"Синдром Чедиака-Хигаси",
"Cheilitis":"хейлит",
"Chelidonium":"Хелидониум",
"Chemical Sensitivity Reduce 1":"Химическая чувствительность Уменьшить 1",
"Chemical Sensitivity Reduce 2":"Уменьшение химической чувствительности 2",
"Chemical Sensitivity":"Химическая чувствительность",
"Chemical Spray-Related Illness":"Болезнь, связанная с химическим распылением",
"Chemicals Green Dye":"Химические вещества Зеленый краситель",
"Chemicals Methotrexate":"Химические вещества Метотрексат",
"Chemtrail Detox 2":"Химтрейл Детокс 2",
"Chemtrail Detox":"Химтрейл Детокс",
"Cherubism":"Херувизм",
"Chest Infection Secondary":"Грудная инфекция вторичная",
"Chest Pain":"Грудная боль",
"Chicken Pox 1":"Ветряная оспа 1",
"Chicken Pox 2":"Ветряная оспа 2",
"Chicken Pox 3":"Ветряная оспа 3",
"Chicken Pox 6":"Ветряная оспа 6",
"Chicken Pox 8":"Ветряная оспа 8",
"Chicken Pox Varicella":"Ветряная оспа Ветряная оспа",
"Chicken Pox":"Ветряная оспа",
"Chilblains":"обморожение",
"Child Disorders":"Детские расстройства",
"Children Diabetes":"Детский диабет",
"Chilomastix Amoeba Cysts":"Кисты Chilomastix Amoeba",
"Chilomastix Cysts (Rat) 2nd":"Кисты хиломастикса (крыса) 2-й",
"Chilomastix Cysts (Rat)":"Кисты хиломастикса (крыса)",
"Chilomonas 2":"Хиломонас 2",
"Chilomonas Whole Mount":"Целая гора Хиломонас",
"Chlamydia General 1":"Хламидия Генерал 1",
"Chlamydia General":"Хламидиоз общий",
"Chlamydia Infections":"Хламидийные инфекции",
"Chlamydia Pneumoniae 1":"Хламидия пневмонии 1",
"Chlamydia Pneumoniae 2":"Хламидия пневмонии 2",
"Chlamydia Pneumoniae 3":"Хламидия пневмонии 3",
"Chlamydia Pneumoniae 4":"Хламидия пневмонии 4",
"Chlamydia Pneumoniae 8":"Хламидия пневмонии 8",
"Chlamydia Trachomatis":"Хламидия трахоматис",
"Chlamydia":"Хламидиоз",
"Chlamydiaceae Infections":"Хламидийные инфекции",
"Chlorine 35cl":"Хлор 35cl",
"Chlorine 37cl":"Хлор 37cl",
"Cholangitis":"Холангит",
"Cholecystitis Chronic":"Холецистит Хронический",
"Cholecystitis":"Холецистит",
"Choledochal Cyst":"Киста холедоха",
"Cholelithiasis":"Желчекаменная болезнь",
"Cholera 2":"Холера 2",
"Cholera 3":"Холера 3",
"Cholera Secondary":"Холера Вторичная",
"Cholera Spirillum":"Холера спириллум",
"Cholera":"холера",
"Cholesteatoma Middle Ear":"Холестеатома среднего уха",
"Cholesteatoma":"Холестеатома",
"Cholesterinum":"Холестерин",
"Chondroectodermal Dysplasia":"Хондроэктодермальная дисплазия",
"Chondroma":"хондрома",
"Chondromalacia Patellae":"Хондромаляция надколенника",
"Chondrosarcoma":"хондросаркома",
"Chordoma":"Хордома",
"Chorea":"Хорея",
"Chorioretinitis":"Хориоретинит",
"Choroideremia":"хориодеремия",
"Chromium cr":"Хром кр",
"Chromium vi":"Хром VI",
"Chromium":"Хром",
"Chromosome 16 Abnormalities":"Аномалии хромосомы 16",
"Chromosome 17 Abnormalities":"Хромосома 17 Аномалии",
"Chromosome 18 Abnormalities":"Хромосома 18 Аномалии",
"Chromosome 20 Abnormalities":"Аномалии хромосомы 20",
"Chromosome 22 Abnormalities":"Аномалии хромосомы 22",
"Chromosome Disorders":"Хромосомные нарушения",
"Chronic Airflow Obstruction":"Хроническая обструкция воздушного потока",
"Chronic Disease":"Хроническое заболевание",
"Chronic Fatigue Syndrome 1":"Синдром хронической усталости 1",
"Chronic Fatigue Syndrome 2":"Синдром хронической усталости 2",
"Chronic Fatigue Syndrome 3":"Синдром хронической усталости 3",
"Chronic Fatigue Syndrome 5":"Синдром хронической усталости 5",
"Chronic Fatigue Syndrome 6":"Синдром хронической усталости 6",
"Chronic Fatigue Syndrome 7":"Синдром хронической усталости 7",
"Chronic Fatigue Syndrome":"Синдром хронической усталости",
"Chronic Fatigue V":"Хроническая усталость V",
"Chronic Fatigue":"Хроническая усталость",
"Chronic Feeling Tired":"Хроническое чувство усталости",
"Chronic Hepatitis":"Хронический гепатит",
"Churg-Strauss Syndrome":"Синдром Чарга-Стросса",
"Cimicifuga":"цимицифуга",
"Circadian Rhythm Resynchronization":"Ресинхронизация циркадного ритма",
"Circulation Diabetic":"Кровообращение Диабетический",
"Circulation Disturbances":"Нарушение кровообращения",
"Circulation Stimulate Increased":"Циркуляция Стимулировать Увеличение",
"Circulation Stimulate Normalized":"Стимуляция кровообращения нормализована",
"Circulation":"Тираж",
"Circulatory Stasis":"Циркуляторный стаз",
"Circulatory System":"Сердечно-сосудистая система",
"Cirrhosis Biliary":"Цирроз желчевыводящих путей",
"Cirrhosis Hepatitis":"Цирроз Гепатит",
"Cirrhosis of the Liver":"Цирроз печени",
"Cladosporium Fulvum 1":"Кладоспориум фулвум 1",
"Cladosporium Fulvum 2":"Кладоспориум фулвум 2",
"Cladosporium Fulvum":"Кладоспориум фульвум",
"Clarity of Spirit":"Ясность духа",
"Clarity of Thought/Mental Function Stimulate":"Ясность мысли/Умственная функция Стимулировать",
"Clark 2.5KHz Zapper Contact":"Clark 2.5KHz Zapper Контакт",
"Clark 2.5KHz Zapper Remote":"Clark 2.5KHz Zapper Remote",
"Clark 30KHz Zapper Contact":"Clark 30KHz Zapper Контакт",
"Clark 30KHz Zapper Remote":"Clark 30KHz Zapper Remote",
"Clark Dual Spectrum Zapper Remote":"Clark Dual Spectrum Zapper Remote",
"Clark Dual Zapper Contact":"Двойной контакт Кларка Zapper",
"Clark Dual Zapper Remote":"Двойной пульт дистанционного управления Clark Zapper",
"Claviceps Purpurea":"Клавицепс пурпурный",
"Clean Blood Plasma":"Чистая плазма крови",
"Cleidocranial Dysplasia":"Ключично-черепная дисплазия",
"Cleverness":"Сообразительность",
"Clogged Auditory Tubes":"Закупорка слуховых труб",
"Clonorchis Sinensis":"Клонорхис китайский",
"Clostridium":"клостридии",




"Difficile":"трудный",
"CMV":"ЦМВ",
"Colitis and Diarrhea":"Колит и диарея",
"Colitis":"Колит",
"Colon Problems General":"Общие проблемы с толстой кишкой",
"Comedones":"комедоны",
"Condylomata Advanced Set":"Расширенный набор кондилом",
"Conjunctivitis":"Конъюнктивит",
"Constipation":"Запор",
"Contusion":"Контузия",
"Convulsions General":"Общие конвульсии",
"Corynebacterium Diphtheriae":"Коринебактерии дифтерии",
"Costalgia":"Костальгия",
"Coughing":"Кашляющий",
"Coxsackie B1":"Коксаки Б1",
"Crohn's and Other Bowel Problems":"Болезнь Крона и другие проблемы с кишечником",
"Crohn's Disease":"Болезнь Крона",
"Cryptococcus Neoformans":"Криптококк неоформанс",
"Cryptosporidium":"криптоспоридий",
"Cyclospora":"Циклоспора",
"Cyst Hydatid":"киста эхинококковая",
"Cystic Fibrosis":"Кистозный фиброз",
"Cystitis Chronic":"Цистит Хронический",
"Cytomegalovirus":"Цитомегаловирус",
"Deafness":"Глухота",
"Dental Foci":"Стоматологические очаги",
"Diphtheria":"Дифтерия",
"Dirofilaria Immitis":"Дирофилярия иммитис",
"Disc Herniated":"Грыжа диска",
"Distortion":"Искажение",
"Diverticulitis Acute":"Дивертикулит острый",
"Diverticulitis":"Дивертикулит",
"Duodenal Ulcer":"Язва двенадцатиперстной кишки",
"Duodenitis":"Дуоденит",
"Dupuytren's Contracture":"Контрактура Дюпюитрена",
"Dysentery":"дизентерия",
"Dysmenorrhea":"Дисменорея",
"Dyspepsia":"Диспепсия",
"E Coli":"кишечная палочка",
"Ear Conditions Various 2":"Заболевания ушей Различные 2",
"Ear Conditions Various":"Заболевания ушей Различные",
"Ear Discharge":"Выделения из уха",
"Ear Diseases":"Ушные заболевания",
"Ear Fungus":"Ушной грибок",
"Ear General Conditions":"Ухо Общие условия",
"Ear Wax":"Ушной воск",
"Earaches":"Ухо болит",
"Ears Balance":"Баланс ушей",
"Ears Discharges":"Выделения из ушей",
"Ears Dizziness":"Уши Головокружение",
"Ears Ringing":"Звон в ушах",
"Eczema 1":"Экзема 1",
"Eczema 2":"Экзема 2",
"Eczema 3":"Экзема 3",
"Eczema Skin Trouble":"Экзема Проблемы с кожей",
"Eczema":"Экзема",
"Edema 1":"Отек 1",
"Elephantiasis":"Слоновость",
"Emphysema":"Эмфизема",
"Encephalitis":"Энцефалит",
"Endometriosis 1":"Эндометриоз 1",
"Endometriosis Chronic":"Эндометриоз хронический",
"Entamoeba Histolytica":"Entamoeba Histolytica",
"Enterobiasis":"энтеробиоз",
"Epicoccum":"эпикокк",
"Epidermophyton Floccinum":"Эпидермофитон флокцинум",
"Epididymitis":"Эпидидимит",
"Epilepsy":"эпилепсия",
"Erysipelas":"Рожа",
"Erythema Nosodum":"Нозодумная эритема",
"Erythema":"Эритема",
"Escherichia Coli":"Кишечная палочка",
"Eustachian Tube Inflammation":"Воспаление евстахиевой трубы",
"Eye Arteriosclerosis":"Артериосклероз глаз",
"Eye Bifocal":"Бифокальный глаз",
"Eye Cataract":"Катаракта глаза",
"Eye Disorders":"Заболевания глаз",
"Eye Droop of Lid":"Опущение век",
"Eye Glaucoma":"Глазная глаукома",
"Eye Infected":"Зараженный глаз",
"Eye Inflammation":"Воспаление глаз",
"Eye Lacrimal":"Глаз слезный",
"Eye Near and Farsighted":"Ближний и дальнозоркий глаз",
"Eye Nerve Pain":"Боль в глазном нерве",
"Eye Ptosis":"Птоз глаз",
"Eye Strain":"Напряжение глаз",
"Eye Swollen Lid":"Опухшие веки глаз",
"Eyes Crossed":"Скрещенные глаза",
"Eyes Glaucoma":"Глаза Глаукома",
"Eyesight to Improve":"Зрение для улучшения",
"Facial Cramps":"Лицевые судороги",
"Facial Paralysis":"Лицевой паралич",
"Facial Toning 1":"Тонирование лица 1",
"Facial Toning 2":"Тонирование лица 2",
"Fainting":"Обморок",
"Felis":"Фелис",
"Fibroadenoma Mamanae":"Фиброаденома Маманае",
"Fibroids General":"Фибромы Общие",
"Fibromyalgia":"Фибромиалгия",
"Fibrosis of Lung":"Фиброз легких",
"Fissures":"Трещины",
"FIV":"ВИК",
"Follicular Mange":"Фолликулярная чесотка",
"Folliculitis Hot Tub":"Гидромассажная ванна для фолликулита",
"Fractures Bone":"Переломы костей",
"Furunculosis":"Фурункулез",
"Fusarium Oxysporum":"Фузариоз оксиспорум",
"Gall Bladder Dystonia With Osteitis":"Дистония желчного пузыря с остеитом",
"Gallbladder Inflammation":"Воспаление желчного пузыря",
"Gallbladder Pain":"Боль в желчном пузыре",
"Gallstones":"Желчные камни",
"Gastritis and Flatus":"Гастрит и вздутие живота",
"German Measles Rubella":"Краснуха, корь, краснуха",
"German Measles Secondary":"Корь красная вторичная",
"Giardia":"лямблии",
"Gingivitis":"Гингивит",
"Glandular Fever":"Железистая лихорадка",
"Glaucoma 3":"Глаукома 3",
"Goiter 1":"Зоб 1",
"Gonads Inflammation 1":"Воспаление половых желез 1",
"Gonorrhea":"Гонорея",
"Gout":"Подагра",
"Granuloma Dent":"Гранулема Дент",
"Gravel In Urine 1":"Гравий в моче 1",
"Gum Disease":"Заболевания десен",
"Heliobacter Pylori 2":"Гелиобактер Пилори 2",
"Heliobacterium Pylori Ulcer":"Язва гелиобактерии пилори",
"Hemophilia 2":"Гемофилия 2",
"Hemorrhage 1":"Кровотечение 1",
"Hemorrhoids":"Геморрой",
"Hepatitis A 2":"Гепатит А 2",
"Hernia Disc":"Грыжа межпозвоночного диска",
"Hip Pain":"Боль в бедре",
"Histoplasma":"гистоплазма",
"Hives":"Ульи",
"Hookworm":"Анкилостома",
"Hordeolum":"ячмень",
"Hot Tub Folliculitis 5":"Фолликулит в горячей ванне 5",
"Hyperacidity Stomach 2":"Повышенная кислотность желудка 2",
"Hyperosmia":"Гиперосмия",
"Hyperthyroid 1":"Гипертиреоз 1",
"Hypothyroid 1":"Гипотиреоз 1",
"Hypoxia":"Гипоксия",
"Immune System Stimulation 3":"Стимуляция иммунной системы 3",
"Intercostal Neuralgia":"Межреберная невралгия",
"Intermittent Claudication":"Перемежающаяся хромота",
"Intestinal Problems Colon":"Проблемы с кишечником",
"Intestinal Problems General":"Общие проблемы с кишечником",
"Intestines Inflammation":"Воспаление кишечника",
"Irritable Bowel Syndrome":"Синдром раздраженного кишечника",
"Jaundice":"Желтуха",
"Jock Itch":"Паховая эпидермофития",
"Joint Inflammation":"Воспаление суставов",
"Kidney Insufficiency":"Почечная недостаточность",
"Kidney Papilloma":"Папиллома почки",
"Kidney Stones":"Камни в почках",
"Kidney Tonic General":"Общий тоник для почек",
"Kieferosteitis":"Киферостеит",
"Klebsiella Pneumoniae":"Клебсиелла пневмонии",
"Knee Joint Pain":"Боль в коленном суставе",
"Large Intestine Tonic":"Тоник для толстой кишки",
"Larynx":"Гортань",
"Legionella":"Легионелла",
"Leishman-Donovan Bodies":"Тела Лейшмана-Донована",
"Leprosy":"проказа",
"Leptospirosis":"Лептоспироз",
"Leukemia":"Лейкемия",
"Leukoderma Acquired":"Приобретенная лейкодерма",
"Leukoencephalitis":"лейкоэнцефалит",
"Leukoplakia":"лейкоплакия",
"Liver Enlargement":"Увеличение печени",
"Liver Flukes":"Печеночные сосальщики",
"Liver Stores Bile Cholesterol":"Печень хранит желчь Холестерин",
"Liver Support":"Поддержка печени",
"Lockjaw":"Тризм",
"Low Blood Pressure":"Низкое кровяное давление",
"Luesinum and Syphilinum":"Луезин и Сифилин",
"Lumbago":"Люмбаго",
"Lung Abscess":"Абсцесс легкого",
"Lung General":"Легкий генерал",
"Lung Sinus Bacteria":"Бактерии пазухи легких",
"General":"Общий",
"Luxation":"Вывих",
"Lymphangitis":"Лимфангит",
"Lymphogranuloma":"лимфогранулема",
"Lymphs and Detox":"Лимфы и Детокс",
"Malabsorption Syndrome":"Синдром мальабсорбции",
"Malassezia Furfur":"Малассезия Фурфур",
"Mange Follicular":"Чесотка фолликулярная",
"Meniere's Disease 1":"Болезнь Меньера 1",
"Meniere's Disease":"Болезнь Меньера",
"Meningioma":"Менингиома",
"Meningitis":"Менингит",
"Microsporum Audouini":"Микроспорум Аудуини",
"Molluscum Contagiosum":"Контагиозный моллюск",
"Morbus Parkinson":"Морбус Паркинсон",
"Mouth Eruptions Herpes Sores":"Рот Высыпания Герпес Язвы",
"Mouth Eruptions White Patches":"Ротовая сыпь Белые пятна",
"Mucormycosis":"Мукормикоз",
"Mucous Membrane General Inflammation":"Общее воспаление слизистой оболочки",
"Multiple Sclerosis 1":"Рассеянный склероз 1",
"Multiple Sclerosis 2":"Рассеянный склероз 2",
"Multiple Sclerosis 3":"Рассеянный склероз 3",
"Multiple Sclerosis 4":"Рассеянный склероз 4",
"Multiple Sclerosis 5":"Рассеянный склероз 5",
"Multiple Sclerosis 6":"Рассеянный склероз 6",
"Multiple Sclerosis Secondary":"Вторичный рассеянный склероз",
"Multiple Sclerosis Stiff Legs":"Рассеянный склероз Неподвижные ноги",
"Multiple Sclerosis Tremor Or Twitch":"Рассеянный склероз Тремор или подергивание",
"Multiple Sclerosis V":"Рассеянный склероз V",
"Mumps Secondary":"Свинка вторичная",
"Mumps Tertiary":"Свинка Третичная",
"Mumps":"Свинка",
"Muscles to Relax":"Мышцы для расслабления",
"Muscular Pain and Injury":"Мышечная боль и травмы",
"Mycobacterium Avium":"Микобактерии Авиум",
"Myositis":"Миозит",
"Nephritis":"Нефрит",
"Nerve Disorders and Neuropathy":"Нервные расстройства и невропатия",
"Neuralgia Intercostal":"Межреберная невралгия",
"Neuralgia Trigeminal":"Невралгия тройничного нерва",
"Neuralgia":"невралгия",
"Neurosis":"Невроз",
"Nocardia Asteroides":"Нокардия Астероидес",
"Orchitis":"орхит",
"Ornithosis":"Орнитоз",
"Osteitis 2":"Остеит 2",
"Osteitis":"остит",
"Osteoarthritis":"Остеоартрит",
"Osteomyelitis":"Остеомиелит",
"Otitis Externa":"Наружный отит",
"Otitis Medinum":"Средний отит",
"Otitis":"Отит",
"Otosclerosis":"Отосклероз",
"Ovarian Cyst":"киста яичника",
"Ovarian Disorders General":"Заболевания яичников Общие",
"Ovarian Elimination Stimulation":"Стимуляция элиминации яичников",
"Palsy General":"Общий паралич",
"Pancreas":"поджелудочная железа",
"Pancreatic Insufficiency":"Панкреатическая недостаточность",
"Papilloma Kidney":"Папиллома почки",
"Paralysis from Stroke":"Паралич от инсульта",
"Paralysis Nonspastic":"Паралич Неспастический",
"Paralysis Spastic":"Паралич Спастический",
"Parasites Brain and Spinal Flukes":"Паразиты головного и спинного мозга",
"Parasites Enterobiasis":"Паразиты Энтеробиоз",
"Parasites Filariose":"Филяриозные паразиты",
"Parasites Follicular Mange":"Паразиты Фолликулярная чесотка",
"Parasites General Flukes":"Паразиты Общие сосальщики",
"Parasites Giardia":"Паразиты лямблии",
"Parasites Heartworms":"Паразиты Сердечные черви",
"Parasites Helminthosporium":"Паразиты Гельминтоспориоз",
"Parasites Hookworm":"Паразиты Анкилостомы",
"Parasites Intestinal Flukes":"Паразиты Кишечные сосальщики",
"Parasites Leishmania Braziliensis":"Паразиты Leishmania Braziliensis",
"Parasites Leishmania Donovan":"Паразиты Leishmania Donovan",
"Parasites Liver Flukes":"Паразиты Печеночные сосальщики",
"Parasites Lymph Flukes":"Паразиты Лимфатические сосальщики",
"Parasites Pancreatic Flukes":"Паразиты Панкреатические сосальщики",
"Parasites Roundworm General":"Общие сведения о паразитах аскаридах",
"Parasites Scabies":"Паразиты Чесотка",
"Parasites Schistosoma Haematobium":"Паразиты Schistosoma Haematobium",
"Parasites Schistosoma Mansoni":"Паразиты Schistosoma Mansoni",
"Parasites Sheep Liver Flukes":"Паразиты овечьей печени",
"Parasites Strongyloides":"Паразиты Strongyloides",
"Parasites Taenia":"Паразиты Taenia",
"Parasites Tapeworms Echinococcinum":"Паразиты Ленточные черви Echinococcinum",
"Parasites Tapeworms Secondary":"Паразиты Ленточные черви Вторичные",
"Parasites Tapeworms":"Паразиты Ленточные черви",
"Parasites Threadworm":"Паразиты",
"Parasites Trichinosis":"Паразиты Трихинеллез",
"Paresis":"Парез",
"Parkinson's Disease":"Болезнь Паркинсона",
"Parvovirus Canine":"Собачий парвовирус",
"Disease":"Болезнь",
"Pemphigus":"Пузырчатка",
"Pericarditis":"Перикардит",
"Periodontal Disease":"Парадантоз",
"Pharyngitis":"Фарингит",
"Phlebitis":"Флебит",
"Plasmacytoma":"Плазмоцитома",
"Pleurisy":"Плеврит",
"Pneumonia Bronchial":"Пневмония бронхиальная",
"Pneumonia General":"Общая пневмония",
"Pneumonia General V":"Общая пневмония V",
"Pneumonia Klebsiella":"Клебсиеллезная пневмония",
"Pneumonia Walking":"Пневмония Ходьба",
"Pneumonia":"Пневмония",
"Pneumovirus":"пневмовирус",
"Polyarthritis":"Полиартрит",
"Polyp Nasal":"Полип Носовой",
"Proctitis":"проктит",
"Psoriasis Ankylosing Spondylitis":"Псориаз Анкилозирующий спондилоартрит",
"Psoriasis":"Псориаз",
"Pullularia Pullulans":"Пулулярия Пуллуланс",
"Pulmonary Fibrosis":"Легочный фиброз",
"Pyelitis Proteus":"пиелит протей",
"Pyoderma":"Пиодермия",
"Pyorrhea":"пиорея",
"Rabies":"Бешенство",
"Ragweed":"Амброзия",
"Raynaud's Disease":"Болезнь Рейно",
"Respiratory Syncytial Virus":"Респираторно-синцитиальный вирус",
"Rheumatoid Arthritis":"Ревматоидный артрит",
"Rhinopneumonitis":"Ринопневмонит",
"Rhizopus Nigricans":"Rhizopus Nigricans",
"Ringworm":"Стригущий лишай",
"Sarcoidosis":"Саркоидоз",
"Sars 1":"Сарс 1",
"Scabies":"Чесотка",
"Schizophrenia Paranoid 1":"Шизофрения Параноидальная 1",
"Sciatica 1":"Ишиас 1",
"Sclerosis Lateral":"Боковой склероз",
"Seizures":"Судороги",
"Shingles":"Опоясывающий лишай",
"Sinus Bacteria":"Синусовые бактерии",
"Spasms Muscle":"Мышечные спазмы",
"Spleen Enlarged":"Селезенка увеличена",
"Spleen Secondary":"Селезенка вторичная",
"Stomatitis Aphthous 1":"Стоматит Афтозный 1",
"Stomatitis Aphthous V":"Стоматит Афтозный V",
"Stomatitis Aphthous":"Стоматит Афтозный",
"Stomatitis":"Стоматит",
"Streptococcus Enterococcinum":"стрептококк энтерококцинум",
"Stye":"Стай",
"Subluxation Induced Disorders":"Заболевания, вызванные подвывихом",
"Swimmers Ear":"Ухо пловца",
"Tachycardia":"Тахикардия",
"Tendomyopathy":"тендомиопатия",
"Tennis Elbow":"Теннисный локоть",
"Thrombophlebitis":"Тромбофлебит",
"Thymus Stimulation":"Стимуляция тимуса",
"Tinea Versicolor":"Опоясывающий лишай",
"Tinnitus":"шум в ушах",
"Tonsillitis":"Тонзиллит",
"Tooth Extraction Follow Up":"Последующее удаление зуба",
"Toothache":"Зубная боль",
"Trachoma":"Трахома",
"Trench Mouth":"Траншейный рот",
"Trichomonas":"Трихомонады",
"Trigeminal Neuralgia":"Невралгия тройничного нерва",
"Tuberculosis Aviare":"Туберкулез Авиаре",
"Tuberculosis Bovine":"Туберкулез крупного рогатого скота",
"Tuberculosis General":"Туберкулез Общие",
"Tuberculosis Klebsiella":"Туберкулез Клебсиелла",
"Tuberculosis Rod E Coli Infections":"Туберкулез, палочки кишечной палочки, инфекции",
"Tuberculosis Rod Form":"Туберкулезная палочка",
"Tuberculosis Secondary Complications":"Вторичные осложнения туберкулеза",
"Tuberculosis Virus Form":"Форма вируса туберкулеза",
"Tumor Brain":"Опухоль головного мозга",
"Ulcer Duodenal":"Язва двенадцатиперстной кишки",
"Ulcer Gastric":"Язва желудка",
"Ulcer Ventricular":"Язва желудочковая",
"Ulcers General":"Язвы Общие",
"Uremia":"Уремия",
"Urethritis":"Уретрит",
"Urticaria":"Крапивница",
"Vaginosis":"вагиноз",
"Varicoses 1":"Варикоз 1",
"Verruca":"Веррука",
"Vertigo":"Головокружение",
"Vision Poor":"Плохое зрение",
"Vitiligo":"витилиго",
"Warts Condyloma":"Бородавки Кондиломы",
"Warts General":"Бородавки генерал",
"Warts Papilloma Type Branch Or Stalk":"Бородавки папилломы типа ветви или стебля",
"Warts Plantar":"Подошвенные бородавки",
"Warts Verruca":"Бородавки Веррука",

};