const categories={
"All":"",
"Adrenals":"Adrenals",
"Allergies":"Allergies",
"Anus":"Anus",
"Anus Rectum":"Anus Rectum",
"Appendix":"Appendix",
"Back":"Back",
"Bladder":"Bladder",
"Blood":"Blood",
"Blood Dogs":"Blood Dogs",
"Blood Organs":"Blood Organs",
"Blood Tissue":"Blood Tissue",
"Bone":"Bone",
"Bone Tissue":"Bone Tissue",
"Bowel":"Bowel",
"Brain":"Brain",
"Breast":"Breast",
"Cancer":"Cancer",
"Cats":"Cats",
"Chest":"Chest",
"Colon":"Colon",
"DNA":"DNA",
"Dogs":"Dogs",
"Ear":"Ear",
"Elbow":"Elbow",
"Energy":"Energy",
"Eye":"Eye",
"Eyes":"Eyes",
"Face":"Face",
"Feet":"Feet",
"Fingers":"Fingers",
"Food":"Food",
"Gallbladder":"Gallbladder",
"Groin":"Groin",
"Gums":"Gums",
"Hair":"Hair",
"Hair Skin":"Hair Skin",
"Hands":"Hands",
"Hands Feet":"Hands Feet",
"Heart":"Heart",
"Hip":"Hip",
"Immune System":"Immune System",
"Immune system":"Immune system",
"Indigestion":"Indigestion",
"Intestines":"Intestines",
"Jaw":"Jaw",
"Joints":"Joints",
"Kidney":"Kidney",
"Knee":"Knee",
"Liver":"Liver",
"Liver Spleen":"Liver Spleen",
"Low Oxygen":"Low Oxygen",
"Lung":"Lung",
"Lung Kidney":"Lung Kidney",
"Lungs Etc":"Lungs Etc",
"Lungs Lymph":"Lungs Lymph",
"Lungs Stomach Intestines":"Lungs Stomach Intestines",
"Lymph":"Lymph",
"Menstruation":"Menstruation",
"Mental":"Mental",
"Mouth":"Mouth",
"Mouth Skin Intestines":"Mouth Skin Intestines",
"Muscle":"Muscle",
"Neck":"Neck",
"Nerve":"Nerve",
"Nerve Eye":"Nerve Eye",
"Nose":"Nose",
"Oral":"Oral",
"Oral Cavity":"Oral Cavity",
"Organ Linings":"Organ Linings",
"Ovary":"Ovary",
"Pancreas":"Pancreas",
"Pancreas Liver Intestines":"Pancreas Liver Intestines",
"Parrots":"Parrots",
"Prostate":"Prostate",
"Respiratory":"Respiratory",
"Rib":"Rib",
"Salivary Glands":"Salivary Glands",
"Shoulder":"Shoulder",
"Skin":"Skin",
"Skin Liver Spleen":"Skin Liver Spleen",
"Skin Lung Intestines":"Skin Lung Intestines",
"Skin Luns Intestines":"Skin Luns Intestines",
"Sleep":"Sleep",
"Spine":"Spine",
"Spine Pelvis":"Spine Pelvis",
"Spleen":"Spleen",
"Stomach":"Stomach",
"Syphilis":"Syphilis",
"Teeth":"Teeth",
"Tendon":"Tendon",
"Testicle":"Testicle",
"Throat":"Throat",
"Thyroid Gland":"Thyroid Gland",
"Toe":"Toe",
"Tonsils":"Tonsils",
"Urethra":"Urethra",
"Uterus":"Uterus",
"Vaginal":"Vaginal",
"Various":"Various",
"Veins":"Veins",
"Viral":"Viral",
"Voice Box":"Voice Box",
"Womb":"Womb",

};
